### ISSUE TITLE
User Story 4: Compare Matches

### ISSUE THREAD

**Issue by augustinanders** [augustinanders/2023_03_01_capstone-neuefische_memory#4]
#### Value Proposition

**As a**  user...

**I want to** reveal 2 cards per turn...

**so that** so that i can check if they match.

#### Acceptance Criteria

- [ ] after revealing 2 cards, they should get compared  🖼️
    - [ ] if the cards match, they get replaced by whitespace 🖼️
    - [ ] else  the cards turn around again 🖼️

#### Tasks

- [ ] First Task..
- ..

#### WireFrame

![Image](https://user-images.githubusercontent.com/121796762/229144962-e58a33c3-7a05-4312-9e20-726582eec7fb.png)

**Comment by augustinanders** [comment]
Thank you for the feedback. Changed it now so the user can decide when to go for the next turn(on the third click).

**Comment by manukao** [comment]
"so that so that i can check if they match." fix typo
